### ISSUE TITLE
Ice does not work with  higan/icarus v095

### ISSUE THREAD

**Issue by ghastmask** [scottrice/Ice#308]
Basically icarus now creates a folder for each rom "Foo.fc" for famicom "Foo.sfc" for super famicom. The ROMFinder calls files_in_directory, which filters out directories.

As a temporary workaround I patched filesystem.py file_in_directory to also return subdirectories. I then changed rom.py to check if self.extenions == "" and os.path.isfile(path) return True.

This way by default subdirectories won't be matched unless you specify an extension. Seems like a hack but it got it working.

**Comment by xeroxpickles** [comment]
Can you post the exact code of rom.py? My python knowledge is pretty limited, so I'm having trouble figuring out where you put if self.extenions == "" and os.path.isfile(path) return True

**Comment by ghastmask** [comment]
Yeah I will post the code tomorrow night or this weekend.

**Comment by ghastmask** [comment]
I pushed the patch to my fork: https://github.com/ghastmask/Ice/commit/020977fef804fbbec6a6d93d27704da656c256ab

**Comment by cpence** [comment]
Also having the same issue. For more info, you can check out the [game paks](byuu.org/emulation/higan/game-paks) page on the higan website; the "file extensions" are still the same (intending to retain cross-compatibility for cases like this), but obviously the file search now needs to match folders. Would love to see this patch integrated!
